# Data:
#   name: test
#   path_csv: "/home/takaogahara/takaogahara/yliopisto/bace.csv"
#   path_joblib: "/home/takaogahara/takaogahara/yliopisto/placeholder_brics/output/test/data.joblib"
#   trials: 300
#   epochs: 50
#   batch_size: 128
#   model: attentive
#   patience: 25
#   loader: decompose
#   checkpoint_path: None

# Tune:
#   hidden_channels:
#     min: 32
#     max: 512
#   num_layers:
#     min: 1
#     max: 3
#   num_timesteps: # heads
#     min: 1
#     max: 3
#   dropout_rate:
#     min: 0.1
#     max: 0.6
#   learning_rate:
#     value: 1e-3
#   weight_decay:
#     value: 1e-5
#   beta_1:
#     value: 0.9
#   beta_2:
#     value: 0.999
#   eps:
#     value: 1e-8

Data:
  name: test
  path_csv: "/home/takaogahara/takaogahara/yliopisto/bace.csv"
  path_joblib: "/home/takaogahara/takaogahara/yliopisto/placeholder_brics/output/test/data.joblib"
  trials: 300
  epochs: 50
  batch_size: 128
  model: attentive
  patience: 25
  loader: decompose
  checkpoint_path: /home/takaogahara/takaogahara/yliopisto/placeholder_brics/output/test/trial_232/best_model.pt
  method: shapley

Tune:
  hidden_channels:
    value: 383
  num_layers:
    value: 2
  num_timesteps: # heads
    value: 2
  dropout_rate:
    value: 0.260308543507782
  learning_rate:
    value: 1e-3
  weight_decay:
    value: 1e-5
  beta_1:
    value: 0.9
  beta_2:
    value: 0.999
  eps:
    value: 1e-8
