Data:
  name: test
  file_path: "path/to/csv_file.csv"
  trials: 2
  epochs: 2
  batch_size: 128
  model: gat
  patience: 8
  loader: default
  checkpoint_path: None

Tune:
  hidden_channels:
    min: 32
    max: 512
  num_layers:
    min: 1
    max: 3
  heads:
    min: 1
    max: 3
  dropout_rate:
    min: 0.1
    max: 0.6
  learning_rate:
    value: 1e-3
  weight_decay:
    value: 1e-5
  beta_1:
    value: 0.9
  beta_2:
    value: 0.999
  eps:
    value: 1e-8
