Data:
  name: None
  task: Classification
  path_csv: "path/to/csv_file.csv"
  path_joblib: "path/to/joblib_file.joblib"
  path_checkpoint: "path/to/checkpoint.pt"
  trials: 2
  epochs: 10
  model: gat # gcn, gat, attentive
  batch_size: 128
  patience: 5
  loader: default  # "default" or "decompose"

Tune:
  hidden_channels:
    min: 32
    max: 512
  num_layers:
    min: 1
    max: 3
  heads:
    min: 1
    max: 3
  dropout_rate:
    min: 0.1
    max: 0.6
  learning_rate:
    value: 1e-3
  weight_decay:
    value: 1e-5
  beta_1:
    value: 0.9
  beta_2:
    value: 0.999
  eps:
    value: 1e-8
